#!/bin/bash
# Developed by Wagner Souza
# https://www.linkedin.com/in/wfscybersecurity/

# The parameterization of these scripts has the purpose of automating the installation of zabbix server 5.2 with grafana 7.0. Approved in the Debian 10 distribution
# Before executing this script, change the password information regarding the creation of the database with the password you want to use

source /etc/profile

# Required packages

apt-get update && apt-get upgrade -y

apt-get install apache2 apache2-utils mariadb-server mariadb-client build-essential vim curl wget -y


# Download zabbix package

wget --no-check-certificate https://repo.zabbix.com/zabbix/5.2/debian/pool/main/z/zabbix-release/zabbix-release_5.2-1%2Bdebian10_all.deb
dpkg -i zabbix-release_5.2-1+debian10_all.deb  

apt-get update 
apt-get install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-agent -y


# Session create database

mysql -u root -p121083 -e "create database zabbix character set utf8 collate utf8_bin; create user zabbix@localhost identified by 'P@ssw0rd'; grant all privileges on zabbix.* to 'zabbix'@'localhost' identified by 'P@ssw0rd'; flush privileges;"

zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mariadb -uzabbix -pP@ssw0rd zabbix


# Add database password

sed -i 's/# DBPassword=/DBPassword=P@ssw0rd/' /etc/zabbix/zabbix_server.conf 


# Changing apache.conf settings

sed -i 's/php_value memory_limit 128M/php_value memory_limit 512M/' /etc/zabbix/apache.conf 
sed -i 's/php_value post_max_size 16M/php_value post_max_size 48M/' /etc/zabbix/apache.conf 
sed -i 's/php_value upload_max_filesize 2M/php_value upload_max_filesize 24M/' /etc/zabbix/apache.conf
sed -i 's/# php_value date.timezone Europe\/\Riga/php_value date.timezone America\/\Recife/' /etc/zabbix/apache.conf

# Hiding the web server information 

sed -i 's/ServerTokens OS/ServerTokens Prod/' /etc/apache2/conf-available/security.conf
sed -i 's/ServerSignature On/ServerSignature Off/' /etc/apache2/conf-available/security.conf


# Restart of services

systemctl enable zabbix-server zabbix-agent
systemctl restart zabbix-server zabbix-agent apache2


# Installing Grafana

apt-get install gnupg2 apt-transport-https software-properties-common -y

wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list

apt-get update 
apt-get install grafana -y

sed -i 's/;allow_loading_unsigned_plugins =/allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource/' /etc/grafana/grafana.ini

grafana-cli plugins install alexanderzobnin-zabbix-app 

systemctl daemon-reload
systemctl enable grafana-server
systemctl start grafana-server


echo "--- Installation completed successfully! :) Access your browser to finish configuring Zabbix and Grafana ---"
